# Generated by Django 5.1.5 on 2025-05-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rarity',
            field=models.CharField(choices=[('gold', 'Gold'), ('amethyst', 'Amethyst'), ('diamond', 'Diamond')], default='gold', max_length=20),
        ),
    ]
