# Generated by Django 5.1.4 on 2025-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_player_bio_player_experience_years_player_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='arena_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
