# Generated by Django 5.1.4 on 2025-01-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_team_logo_url_team_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='player_pictures/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(upload_to='team_logos/'),
        ),
    ]
