# Generated by Django 5.1.5 on 2025-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_player_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='skill_breakdown',
        ),
        migrations.AddField(
            model_name='player',
            name='best_skill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
